### PR TITLE
Add scan file for hk-HongKong

### PR DESCRIPTION
**Pull request by z1022**
RTHK (band 62)
[CHANNEL]
DELIVERY_SYSTEM = DVBT
FREQUENCY = 802000000
BANDWIDTH_HZ = 8000000
CODE_RATE_HP = AUTO
CODE_RATE_LP = NONE
MODULATION = QAM/64
TRANSMISSION_MODE = 8K
GUARD_INTERVAL = 1/32
HIERARCHY = NONE
INVERSION = AUTO

### CODE REVIEW

**Comment by oliv3r** [comment]
@z1022 can you please rebase your branch?

**Comment by KellerNET** [comment]
The frequencies of es-Asturias are: http://www.tdt1.com/canales-asturias/
802Mhz does not work.
The new frequencies are in the previous link.

**Comment by oliv3r** [comment]
There seems to be a lot of changes completly unrelated to hk-HongKong, can you rebase the request and only put in the PR what is actually intended?

**Comment by KellerNET** [comment]
Okay, I got it automated.
I have to change the code :-)
This weekend I'm done.
The DVB-T channels in Spain have all changed.
Thanks for everything.
Sorry for my English
 :(

**Comment by oliv3r** [comment]
This PR has turned into a mess. I'd be very happy to merge your changes, but they are currently just to outdated. Either rebase and resubmit or open a new PR.

**Pull request closed without merging**
