### PR TITLE
Updated channels and regions of Spain 2016

### PR DESCRIPTION
**Pull request by KellerNET**
Replaced by es-Vitoria-Gasteiz file es-Alava.
Contains all the tunes Alava.

### CODE REVIEW

**Comment by KellerNET** [comment]
Frecuency http://www.tdt1.com/

**Comment by KellerNET** [comment]
All frequencies in Spain updated and completed.

**Comment by oliv3r** [comment]
Hey KellerNET,

I've just spent the last 1 1/2 hours to fix-up your pull-request, but its a little bit too messy :)

I think most of these changes could go into one big commit (rework tables spain or something) and remove all erroneous whitespaces. (CR are all over the place and new line errors).

Thanks.

**Comment by KellerNET** [comment]
Ok. I'll fix it.
Thanks for you job. :-)

**Comment by oliv3r** [comment]
Hi KellerNET,

it seems your patch-set is still quite big and messy. If you need your changes to be added, please open up a new PR with updated content.

**Pull request closed without merging**
